# =====================
# Configurações globais
# =====================
jwt:
  secret: secret
  expiration: 604800
  header: Authorization

# =========================
# Perfil de desenvolvimento
# =========================
spring:
  profiles:
    active: dev

---

# ==================
# Perfil de produção
# ==================
spring:
  profiles: prod

---

# ===============
# Perfil de teste
# ===============
spring:
  profiles: test